[package]
name = "only-comments"
version = "0.2.0"
authors = ["Ross Nomann <rossnomann@protonmail.com>"]
edition = "2021"

[dependencies]
carapax = "0.11.0"
dotenv = "0.15.0"
env_logger = "0.9.0"
log = "0.4.14"
tokio = { version = "1.16.1", features = ["macros", "rt-multi-thread"] }
