[package]
name = "only-comments"
version = "0.1.0"
authors = ["Ross Nomann <rossnomann@protonmail.com>"]
edition = "2018"

[dependencies]
carapax = "0.10.0"
dotenv = "0.15.0"
env_logger = "0.8.2"
log = "0.4.14"
tokio = { version = "1.1.1", features = ["macros", "rt-multi-thread"] }
